-- type: flyyx
local user_words = {
    ["修仙"] = "xqxm",
    ["候选栏"] = "hxlj",
    ["候选框"] = "hxkl",
    ["凡人修仙传"] = "frxv",
    ["吞噬星空"] = "tuxk",
    ["周予"] = "vzyu",
    ["咱孩"] = "zjhd",
    ["姜太虚"] = "jtxu",
    ["季欢"] = "jihr",
    ["安印"] = "anyb",
    ["实名"] = "uimk",
    ["实践是检验真理的唯一标准"] = "ujuv",
    ["宫保"] = "gsbc",
    ["山海八荒录"] = "uhbl",
    ["巴萨"] = "basa",
    ["形码"] = "xkma",
    ["悟空"] = "wuks",
    ["曼城"] = "mjig",
    ["格式化"] = "guhx",
    ["江湖夜雨十年灯"] = "jhyd",
    ["洛水"] = "louv",
    ["皇马"] = "hlma",
    ["直聘"] = "vipb",
    ["签章"] = "qmvh",
    ["编辑器"] = "bjqi",
    ["自造词"] = "zzci",
    ["虎码"] = "huma",
    ["音托"] = "ybto",
}
return user_words