-- type: flyyx
local user_words = {
    ["一场梦"] = "yimg",
    ["仙逆"] = "xmni",
    ["俺宝"] = "anbc",
    ["出简"] = "iujm",
    ["出简让全"] = "ijrq",
    ["叶凡"] = "yefj",
    ["宝子"] = "bczi",
    ["有坂"] = "yzbj",
    ["梅西"] = "mwxi",
    ["梦中界"] = "mvjp",
    ["横跳"] = "hgtn",
    ["欧国联"] = "oglm",
    ["滑跪"] = "hxgv",
    ["爱涂鸦的蜗牛"] = "atyn",
    ["独体字"] = "dtzi",
    ["相交"] = "xljn",
    ["真谛"] = "vfdi",
    ["知北游"] = "vbyz",
    ["神识"] = "ufui",
    ["自我解构"] = "zwjg",
    ["自然码"] = "zrma",
    ["让全"] = "rhqr",
    ["通天教主"] = "ttjv",
    ["道祖"] = "dczu",
    ["鹤形"] = "hexk",
}
return user_words