local user_words = {
    ["串击"] = "ddum",
    ["候选项"] = "jquw",
    ["元瑶"] = "mpny",
    ["冬去春来"] = "hgaa",
    ["前二"] = "hvme",
    ["司徒南"] = "awnm",
    ["啼魂"] = "diba",
    ["大的"] = "mdun",
    ["小金鱼"] = "yzwv",
    ["有坂"] = "nvgx",
    ["武指"] = "fpuv",
    ["没苦硬吃"] = "klmd",
    ["洗手感"] = "kunf",
    ["空明码"] = "eomn",
    ["紫灵"] = "svbc",
    ["说真的"] = "snun",
    ["速录宝"] = "xbwn",
    ["键值对"] = "zjrk",
    ["韩老魔"] = "nqza",
}
return user_words